spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: "LvLgBDoxDkpt12w_uWf4"
            client-secret: "jYPs9EzRZI"
            scope:
              - name
              - email
          #- profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/auth/login/oauth2/naver #코드를 받는 uri(naver 의 콜백 uri)


        provider: #네이버의 provider는 등록되어 있지 않아 사용자가 등록해야된다.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize #네이버 로그인 창을 받을수 있다
            token-uri: https://nid.naver.com/oauth2.0/token #토큰을 받는 uri
            user-info-uri: https://openapi.naver.com/v1/nid/me #프로필 주소를 받는 uri
            user-name-attribute: response #회원 벙보를 json 형태로 받는데 response 라는 키값으로 네이버가 리턴해줌
