/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gk891qrsEr3
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Separator } from "@/components/ui/separator"

export function Login() {
  return (
    (<div className="mx-auto max-w-md space-y-6">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Sign In</h1>
        <p className="text-gray-500 dark:text-gray-400">Enter your email and password to sign in</p>
      </div>
      <div className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="email">Email</Label>
          <Input id="email" placeholder="m@example.com" required type="email" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="password">Password</Label>
          <Input id="password" required type="password" />
        </div>
        <Button className="w-full" type="submit">
          Sign In
        </Button>
      </div>
      <div className="flex justify-between text-sm">
        <Link className="underline" href="my-v0/src/components/component#">
          Forgot password?
        </Link>
        <Link className="underline" href="my-v0/src/components/component#">
          Create an account
        </Link>
      </div>
      <Separator className="my-8" />
      <div className="space-y-4">
        <Button className="w-full" variant="outline">
          Sign in with WeChat
        </Button>
        <Button className="w-full" variant="outline">
          Sign in with QQ
        </Button>
      </div>
    </div>)
  );
}
